### ISSUE TITLE
Should I not be using rbenv-installer?

### ISSUE THREAD

**Issue by mattbrictson** [fesplugas/rbenv-installer#1]
I saw some references in recent commits to the README (perhaps jokingly?) that it's not a good idea to use rbenv-installer. I discovered this project by way of [RailsCast #335](http://railscasts.com/episodes/335-deploying-to-a-vps) in 2012 and it has served me well for a couple years now.

Do you have an official stance on whether rbenv-installer is "production ready"?

**Comment by mattbrictson** [comment]
Seems like the right thing to is switch to the official rbenv-installer:

https://github.com/rbenv/rbenv-installer

**Comment by MaxPleaner** [comment]
@mattbrictson as far as I'm aware the official rbenv installer does not also download the ruby versions list, which is why rbenv-installer is appealing.
