### ISSUE TITLE
ubuntu 14.04

### ISSUE THREAD

**Issue by grigoris86** [fesplugas/rbenv-installer#3]
can i use `rbenv bootstrap-ubuntu-12-04` for ubuntu 14.04??

**Comment by mattbrictson** [comment]
I don't think this project is maintained. But yes, I have used it for 14.04 and it works somewhat. You'll also need to install `libffi-dev`.

My suggestion would be to not use the bootstrap script; just manually install the necessary packages for 14.04, which I believe are:

* build-essential
* libffi-dev
* libreadline-gplv2-dev
* libssl-dev
* libxml2
* libxml2-dev
* libxslt1-dev
* tklib
* zlib1g-dev
